//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKulup
    {
        public byte KulupId { get; set; }
        public string kulupAd { get; set; }
    }
}
